SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `oddJobs` DEFAULT CHARACTER SET utf8 ;
USE `oddJobs` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE IF NOT EXISTS `Clients` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `clientName` VARCHAR(200) NOT NULL,
  `clientSurname` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS `Specialists` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `specialistName` VARCHAR(200) NOT NULL,
  `specialistSurname` VARCHAR(100) NOT NULL,
  `specialistProffesion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS `Advertisements` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `advTitle` VARCHAR(200) NOT NULL,
  `advDescription` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1002;